export enum Routes {
  NAVIGATION_TO_HOME_SCREEN = 'HomeScreen',
  NAVIGATION_TO_CATEGORIES_SCREEN = 'CategoriesScreen',
  NAVIGATION_TO_CART_SCREEN = 'CartScreen',
  NAVIGATION_TO_PROFILE_SCREEN = 'ProfileScreen',
  NAVIGATION_TO_PRODUCT_LIST_SCREEN = 'ProductListScreen',
  NAVIGATION_TO_PRODUCT_DETAILS_SCREEN = 'ProductDetailsScreen',
}
